# Generated by Django 4.1.3 on 2022-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=20)),
                ('eemail', models.EmailField(max_length=50)),
                ('econtact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
